export const data = [
  { id: 1, phrase: "Na academia, levantar peso é fácil. Difícil é levantar da cama no dia seguinte! 💪😴" },
  { id: 2, phrase: "Minha relação com a academia é séria… sériamente complicada! 🙄" },
  { id: 3, phrase: "Se abdominal desse dinheiro, eu estaria milionário na academia! 💸😅" },
  { id: 4, phrase: "A academia é o único lugar onde ‘meio quilo a mais’ é motivo de festa! 🎉🍕" },
  { id: 5, phrase: "Na academia, eu sou tipo a lâmpada: demoro a acender, mas quando acendo, ilumino tudo! 💡✨" },
  { id: 6, phrase: "Minha rotina de exercícios é tão intensa que até a barata da academia está em melhor forma que eu! 🏋️‍♂️🐜" },
  { id: 7, phrase: "A única coisa que eu levanto na academia é o cartão para passar na catraca. 💳😅" },
  { id: 8, phrase: "Malhar é como namorar: no começo é difícil, mas depois a gente se acostuma. 💔😂" },
  { id: 9, phrase: "Quando me perguntam se eu malho, eu respondo: ‘Malho, malho mesmo a paciência dos outros!’ 🤷‍♂️😆" },
  { id: 10, phrase: "Na academia, meu maior exercício é a arte de esperar a esteira desocupar. ⌛🏃‍♂️" },
  { id: 11, phrase: "Malhar é fácil, difícil é explicar por que eu estou suando tanto na esteira! 😓🏃‍♂️" },
  { id: 12, phrase: "Sou tão fitness que até a minha pizza é de massa integral! 🍕😅" },
  { id: 13, phrase: "Na academia, meu músculo mais desenvolvido é o da paciência. 🙇‍♂️😅" },
  { id: 14, phrase: "Se for para correr atrás de algo, que seja o delivery de comida! 🏃‍♂️🍔" },
  { id: 15, phrase: "O único six-pack que eu tenho é o de cerveja na geladeira. 🍺😁" },
  { id: 16, phrase: "A única maratona que eu pratico é a de séries na Netflix. 🎬🛋️" },
  { id: 17, phrase: "Estou na academia para fortalecer o músculo do riso, pois rir é o melhor exercício! 😄🏋️‍♂️" },
  { id: 18, phrase: "A única coisa que eu levanto rápido na academia é a mão para pedir ajuda ao instrutor. 🙋‍♂️😆" },
  { id: 19, phrase: "Malho porque adoro a sensação de terminar o treino e ir direto para o sofá. 🛋️😅" },
  { id: 20, phrase: "Minha relação com a academia é como um relacionamento complicado no Facebook: é complicado! 🔄😅" },
  { id: 21, phrase: "Estou na academia para manter a forma… a forma de pizza. 🍕😆" },
  { id: 22, phrase: "Na academia, eu sou o rei do aquecimento. Só. 🔥😅" },
  { id: 23, phrase: "Fiz uma dieta rigorosa: agora só como chocolate com 85% de cacau, porque tem 15% de chance de ser salada. 🍫🥗" },
  { id: 24, phrase: "Malho porque adoro a sensação de terminar o treino e ir direto para o sofá. 🛋️😅" },
  { id: 25, phrase: "O único treino que eu faço regularmente é o treino de paciência na fila da academia. ⌛🏋️‍♂️" },
  { id: 26, phrase: "Meu personal trainer é o sono, e eu pratico todos os dias com maestria! 😴😅" },
  { id: 27, phrase: "Se fazer flexão de gênero fosse um exercício, eu seria atleta olímpico! 🤸‍♂️😆" },
  { id: 28, phrase: "A única coisa que eu levanto na academia com facilidade é a suspeita dos outros. 🤨😅" },
  { id: 29, phrase: "Minha relação com a academia é como um relacionamento complicado no Facebook: é complicado! 🔄😅" },
  { id: 30, phrase: "Estou na academia para manter a forma… a forma de pizza. 🍕😆" },
  { id: 31, phrase: "Na academia, eu sou o rei do aquecimento. Só. 🔥😅" },
  { id: 32, phrase: "Meu objetivo na academia é chegar ao nível avançado de conseguir amarrar o tênis sem perder o fôlego. 🎯👟" },
  { id: 33, phrase: "A única maromba que eu conheço é a do meu liquidificador, fazendo vitamina de banana com whey protein. 🍌🥤" },
  { id: 34, phrase: "Dizem que a prática leva à perfeição. Por isso, pratico a arte de enrolar na academia todos os dias. 🔄🏋️‍♂️" },
  { id: 35, phrase: "Estou na academia para fortalecer o abdômen. O abdômen da geladeira, é claro! 🍔😅" },
  { id: 36, phrase: "Na academia, eu sou um mestre na arte de esquecer a toalha e o squeeze em casa. 🙈🤦‍♂️" },
  { id: 37, phrase: "Dizem que o importante é a saúde. Por isso, escolho a saúde da minha paz de espírito, evitando a academia. Compre vitaminas e suplementos🧘‍♂️😅" },
  { id: 38, phrase: "Na academia, sou especialista em levantar a moral dos outros, não os pesos. 🙌💪" },
  { id: 39, phrase: "Meu personal trainer é tão bom que até os equipamentos da academia ficam surpresos com a criatividade dos exercícios. 🏋️‍♂️😲" },
  { id: 40, phrase: "A única coisa que eu esmago na academia é a vontade de voltar para casa. 😅🏡" },
  { id: 41, phrase: "Minha barriga não é de cerveja, é de malte líquido fermentado. 🍺😁" },
  { id: 42, phrase: "Na academia, eu sou um atleta: atleta de sofá, é claro! 🛋️😅" },
  { id: 43, phrase: "A única coisa que eu malho com afinco é a arte de inventar desculpas para não ir à academia. 🤷‍♂️🤭" },
  { id: 44, phrase: "O único suplemento que eu tomo é o café, para dar energia até o fim do treino… ou pelo menos até a metade. ☕😅" },
  { id: 45, phrase: "Dizem que a prática leva à perfeição. Eu pratico tanto a preguiça que já estou quase perfeito nisso. 🔄😴" },
  { id: 46, phrase: "Na academia, eu sou um atleta: atleta de sofá, é claro! 🛋️😅" },
  { id: 47, phrase: "A única coisa que eu malho com afinco é a arte de inventar desculpas para não ir à academia. 🤷‍♂️🤭" },
  { id: 48, phrase: "A única coisa que eu estico na academia é o tempo que levo para escolher a próxima música na playlist. ⏳🎶" },
  { id: 49, phrase: "Dizem que a prática leva à perfeição. Eu pratico tanto a preguiça que já estou quase perfeito nisso. 🔄😴" },
  { id: 50, phrase: "Na academia, meu desempenho é tão bom que até os pesos ficam surpresos! 🏋️‍♂️😲" }
];